services:
  web:
    build:
      args:
        user: hrsale
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./www:/var/www/html
      - ./www/vendor:/var/www/vendor
      - ./php-config/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: db
    volumes:
      - './docker/volumes/db:/var/lib/mysql'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'ci4'
      MYSQL_ROOT_PASSWORD: '1234'
      MYSQL_PASSWORD: '1234'
      MYSQL_USER: 'ci4'
    ports:
      - "3306:3306"

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - '${FORWARD_REDIS_PORT:-6379}:6379'
    volumes:
      - './docker/volumes/redis/:/data'
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      retries: 3
      timeout: 5s

volumes:
  db_data: